### ISSUE TITLE
Auth ui screen issue

### ISSUE THREAD

**Issue by george-radu-cs** [SolomonFlavius/FrigiderVirtual#11]
In pagina de auth se intampla overflow cand apare tastatura virtuala.

Screen
![adf6b3b4-6e15-490d-9b5f-daf054ce085b](https://user-images.githubusercontent.com/63563144/173128446-f3a8ed02-164e-4b39-bc1e-36ac69441806.jpg)

Posibil fix: micsoreza padding-ul la inputuri | stergem butonul de Remember me.

**Comment by SolomonFlavius** [comment]
Salut George,

Am rezolvat aceasta problema pe ultimul update. Mai am cateva modificari si o sa dau merge.

Merci,
Flavius
