### ISSUE TITLE
Bug visual NAVBAR

### ISSUE THREAD

**Issue by SolomonFlavius** [SolomonFlavius/FrigiderVirtual#7]
Hello baieti,
Am descoperit un bug visual. Cand te autentifici o sa te duca direct pe pagina cu navbarul, aici este o problema vizuala: Butonul de la Products este un patrat cu un X in el, probabil nu citeste bine referinta.
Sper sa se gaseasca solutie pana la urmatorul merge.
O sa las mai jos un link de imgur cu problema zisa.
https://imgur.com/a/ro4tT6x
![image](https://user-images.githubusercontent.com/79804596/172936240-8bb64ffd-5478-4871-9e66-6bd66200b215.png)

Merci,
Flavius

**Comment by DavidArcalianu** [comment]
rezolvat intr-un merge anterior
