### ISSUE TITLE
Un mic typo la fisierele cu retete

### ISSUE THREAD

**Issue by DavidArcalianu** [SolomonFlavius/FrigiderVirtual#8]
Avem typo aici unde am pus cu rosu, atat la numele fisierelor cat si la numele claselor din interior.

![typo](https://user-images.githubusercontent.com/80058486/173047488-134b771e-cfeb-4fca-81da-89f0ae12fc82.jpeg)

**Comment by george-radu-cs** [comment]
la refactor schimbati toate numele fisierelor folosind snake_case

**Comment by DavidArcalianu** [comment]
rezolvat la refactor
